### PR TITLE
localization refactor

### PR DESCRIPTION
**Pull request by tasandberg**
## 🛠️ Changes
Moves the entire localization system from cookie-based to route-based, which means putting *all* of the routes under a top-level `[locale]` dynamic route segment. Hence the huge file change count.

* Overview of the [i18n routing approach](https://next-intl-docs.vercel.app/docs/getting-started/app-router/with-i18n-routing)
* [Further adjustments to enable static rendering](https://next-intl-docs.vercel.app/docs/getting-started/app-router/with-i18n-routing#static-rendering)

It's hard to get a sense of from the "Files Changed" tab, but the new app directory structure looks like this:
image

## 🧪 Testing
A rather thorough clickthrough would be good here, since every route was moved under `[locale]`. Take note of the general feel of navigation.. it should be snappier overall.

### CODE REVIEW

**Comment by eddie-m-m** [comment]
It took some reading (good stuff!), but I think I understand. 

There's gonna be updates (looks like at the least, `defaultMetadata` addition) to do relative to the offices view ticket I just merged into main the other day; do you wanna merge that in and update before I finish a review (I've clicked through everything else as is)?

**Comment by tasandberg** [comment]
Yeah it'd be good to have a full clickthrough after I resolve that merge,
I'll ping you when it's ready. Thanks!!

**Review by eddie-m-m — COMMENTED** [review]
At least the following files still have `Link`s with locales in their hrefs. 

- `ConfirmationModal`
- `SignupForm`
- `ModerationModal`

I first noticed this when getting a 404 attempting to navigate to Terms of Service from various modals.

Image 10-25-24 at 1 16 PM
Image 10-25-24 at 1 16 PM

**Comment by tasandberg** [comment]
@eddie-m-m links fixed, awesome catch 🙇

**Review by eddie-m-m — APPROVED** [review]
I can't find anything wrong. I think it's good to go! (But maybe you'll want to wait for @elchao96  to comb through as well :) )

Also, the account page wasn't included in my click-through because of a redirect to the landing page.

**Pull request merged**
